import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Script } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const leagueScript = League_Script({
  variable: "--font-league-script",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueScript.className} ${leagueScript.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
